<?php

namespace GHOME\CoreBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * LogRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LogRepository extends EntityRepository
{
	public function queryAllOrderedByDate()
	{
		return $this->getEntityManager()
	        ->createQuery(
				'SELECT l FROM GHOMECoreBundle:Log l '.
				'ORDER BY l.time DESC');
	}
}