security:
    encoders:
        GHOME\CoreBundle\Entity\User:
            algorithm: sha1
            encode_as_base64: false
            iterations: 1

    providers:
        administrators:
            entity: { class: GHOMECoreBundle:User, property: username }

    access_control:
        - { path: ^/admin, roles: ROLE_ADMIN }

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false
        login_firewall:
            pattern:    ^/login$
            anonymous:  ~
        secured_area:
            pattern:    ^/
            anonymous:  false
            remember_me:
                key:      fJK6l=3f7qSb5sL
                lifetime: 3600
                path:     /
                domain:   ~
            logout:
                path:   /logout
                target: /
            form_login:
                login_path:  /login
                check_path:  /login_check

    access_control:
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
#        - { path: ^/config, roles: ROLE_ADMIN }
