services:
    ghome_core.twig.extension:
        class: GHOME\CoreBundle\Twig\GHOMEExtension
        tags:
            - { name: twig.extension }
    ghome_core.room_manager:
        class: GHOME\CoreBundle\Entity\RoomManager
        arguments: [%ghome.etc_dir%]
        
    ghome_core.metric_manager:
        class: GHOME\CoreBundle\Entity\MetricManager
        arguments: [%ghome.etc_dir%]
    
    ghome_core.sensor_manager:
        class: GHOME\CoreBundle\Entity\SensorManager
        arguments: [%ghome.etc_dir%, @ghome_core.metric_manager, @ghome_core.room_manager]